import { FoodItem, User } from './types';

export const MOCK_SELLERS: User[] = [
  {
    id: 's1',
    name: 'Chef Ayşe d\'Atelier',
    email: 'ayse@example.com',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    location: 'Beşiktaş, İstanbul',
    rating: 4.9,
    reviewCount: 124,
    isVerified: true,
    bio: 'Anadolu mirasını modern tekniklerle harmanlıyor, her tabağı bir duygu imzasına dönüştürüyoruz.',
    joinDate: 'Ocak 2024',
  },
  {
    id: 's2',
    name: 'Signature d\'Anatolie',
    email: 'fatma@example.com',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    location: 'Kadıköy, İstanbul',
    rating: 4.7,
    reviewCount: 89,
    isVerified: true,
    bio: 'Unun ve suyun kadim dostluğunu, Mezopotamya’nın derin baharatlarıyla yeniden yorumlayan bir lezzet yolculuğu.',
    joinDate: 'Mart 2024',
  },
  {
    id: 's3',
    name: 'L\'Atelier Gastronomique',
    email: 'mutfak@example.com',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    location: 'Şişli, İstanbul',
    rating: 4.5,
    reviewCount: 56,
    isVerified: true,
    bio: 'Doğanın saflığını porselenle buluşturan, mevsimsel ve sürdürülebilir bir gurme deneyimi.',
    joinDate: 'Haziran 2024',
  },
];

export const MOCK_FOOD_ITEMS: FoodItem[] = [
  {
    id: 'f1',
    sellerId: 's1',
    sellerName: 'Chef Ayşe d\'Atelier',
    title: 'Vişne Taneli Ege Esintili Yaprak Sarma',
    description: 'Vişne taneleri ve tarçınla demlenmiş, sızma zeytinyağı ile parlatılmış asma yaprakları.',
    price: 245,
    category: 'Zeytinyağlı Atölyesi',
    cuisineType: 'Ege Mirası',
    dietaryPreferences: ['vejetaryen', 'vegan'],
    flavorProfiles: ['Ferah', 'Umami'],
    occasions: ['Pazar Kahvaltısı', 'Aile Yemeği'],
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 45,
    prepTime: '4 saat',
    isAvailable: true,
    location: 'Beşiktaş, İstanbul',
  },
  {
    id: 'f2',
    sellerId: 's1',
    sellerName: 'Chef Ayşe d\'Atelier',
    title: 'Yavaş Pişmiş Tandır Usulü Kuzu İncik',
    description: '12 saat boyunca damla sakızı ve taze kekikle fırınlanmış, mürdüm eriği soslu kuzu incik.',
    price: 580,
    category: 'Ateş Üstü Lezzetler',
    cuisineType: 'Anadolu Seçkisi',
    dietaryPreferences: [],
    flavorProfiles: ['İsli', 'Karamelize'],
    occasions: ['Özel Davet', 'Romantik Akşam'],
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop',
    rating: 4.8,
    reviewCount: 32,
    prepTime: '12 saat',
    isAvailable: true,
    location: 'Beşiktaş, İstanbul',
  },
  {
    id: 'f3',
    sellerId: 's2',
    sellerName: 'Signature d\'Anatolie',
    title: 'Zırh Kıymalı El Açması Anadolu Mantısı',
    description: 'Zırhla çekilmiş dana eti ve karamelize soğan dolgulu, isli biber yağı ile sunulan el emeği.',
    price: 320,
    category: 'Hamur Sanatı',
    cuisineType: 'Kapadokya Esintisi',
    dietaryPreferences: [],
    flavorProfiles: ['Baharatlı', 'Umami'],
    occasions: ['Aile Yemeği'],
    image: 'https://images.unsplash.com/photo-1626128665085-470a4a4e9a24?w=800&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 28,
    prepTime: '3 saat',
    isAvailable: true,
    location: 'Kadıköy, İstanbul',
  },
  {
    id: 'f4',
    sellerId: 's2',
    sellerName: 'Signature d\'Anatolie',
    title: 'Gaziantep Mirası Altın Dokunuşlu Baklava',
    description: '40 kat şeffaf yufka arasına serpilmiş boz fıstık ve meşe odunu ateşinde demlenmiş şerbet.',
    price: 490,
    category: 'Tatlı Reçeteleri',
    cuisineType: 'Mezopotamya Sanatı',
    dietaryPreferences: ['vejetaryen'],
    flavorProfiles: ['Karamelize'],
    occasions: ['Özel Davet', 'Aile Yemeği'],
    image: 'https://images.unsplash.com/photo-1528605105345-5344ea20e269?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 15,
    prepTime: '1 gün',
    isAvailable: true,
    location: 'Kadıköy, İstanbul',
  },
  {
    id: 'f5',
    sellerId: 's3',
    sellerName: 'L\'Atelier Gastronomique',
    title: 'Zencefilli ve Közlenmiş Sebze Suyu ile Süzme Mercimek',
    description: '36 saat demlenmiş ilikli kemik suyu veya sebze konsantresi ile hazırlanan ipeksi doku.',
    price: 160,
    category: 'Sıvı Cevherler',
    cuisineType: 'Modern Anadolu',
    dietaryPreferences: ['vejetaryen', 'glutensiz'],
    flavorProfiles: ['Ferah', 'Umami'],
    occasions: ['Hızlı Gurme'],
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=600&fit=crop',
    rating: 4.5,
    reviewCount: 12,
    prepTime: '1 saat',
    isAvailable: true,
    location: 'Şişli, İstanbul',
  },
  {
    id: 'f6',
    sellerId: 's3',
    sellerName: 'L\'Atelier Gastronomique',
    title: 'Trüf Yağı ve Mevsimsel Yabani Mantar Senfonisi',
    description: 'Kuzugöbeği ve istiridye mantarlarının trüf esansı ile buluştuğu yüksek besin değerli seçki.',
    price: 450,
    category: 'Bitkisel İmza',
    cuisineType: 'Modern Anadolu',
    dietaryPreferences: ['vejetaryen', 'vegan', 'glutensiz'],
    flavorProfiles: ['Umami', 'İsli'],
    occasions: ['Romantik Akşam', 'Özel Davet'],
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 8,
    prepTime: '1 saat',
    isAvailable: true,
    location: 'Şişli, İstanbul',
  },
];
