import { FoodItem, User } from './types';

export const MOCK_SELLERS: User[] = [
  {
    id: 's1',
    name: 'Ayşe Teyze',
    email: 'ayse@example.com',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1581333100576-b73bbe92c19a?w=400&h=400&fit=crop',
    location: 'Beşiktaş, İstanbul',
    rating: 4.9,
    reviewCount: 124,
    isVerified: true,
  },
  {
    id: 's2',
    name: 'Fatma Hanım',
    email: 'fatma@example.com',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1556911223-e1543433716a?w=400&h=400&fit=crop',
    location: 'Kadıköy, İstanbul',
    rating: 4.7,
    reviewCount: 89,
    isVerified: true,
  },
  {
    id: 's3',
    name: 'Mutfak Sanatları Atölyesi',
    email: 'mutfak@example.com',
    role: 'seller',
    avatar: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=400&fit=crop',
    location: 'Şişli, İstanbul',
    rating: 4.5,
    reviewCount: 56,
    isVerified: false,
  },
];

export const MOCK_FOOD_ITEMS: FoodItem[] = [
  {
    id: 'f1',
    sellerId: 's1',
    sellerName: 'Ayşe Teyze',
    title: 'Ev Yapımı Zeytinyağlı Sarma',
    description: 'İncecik sarılmış, bol limonlu ve taze nane aromalı geleneksel yaprak sarma.',
    price: 120,
    category: 'Zeytinyağlılar',
    cuisineType: 'Ege Mutfağı',
    dietaryPreferences: ['vejetaryen', 'vegan'],
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 45,
    prepTime: '3 saat',
    isAvailable: true,
    location: 'Beşiktaş, İstanbul',
  },
  {
    id: 'f2',
    sellerId: 's1',
    sellerName: 'Ayşe Teyze',
    title: 'Anne Köftesi ve Patates',
    description: 'Özel baharat karışımı ile hazırlanan sulu anne köftesi ve çıtır patates.',
    price: 180,
    category: 'Ana Yemekler',
    cuisineType: 'Türk Mutfağı',
    dietaryPreferences: [],
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&h=600&fit=crop',
    rating: 4.8,
    reviewCount: 32,
    prepTime: '1 saat',
    isAvailable: true,
    location: 'Beşiktaş, İstanbul',
  },
  {
    id: 'f3',
    sellerId: 's2',
    sellerName: 'Fatma Hanım',
    title: 'Kıymalı Mantı',
    description: 'El açması, bol kıymalı ve sarımsaklı yoğurt soslu Kayseri usulü mantı.',
    price: 150,
    category: 'Hamur İşleri',
    cuisineType: 'Anadolu Mutfağı',
    dietaryPreferences: [],
    image: 'https://images.unsplash.com/photo-1616662911021-705701f468b1?w=800&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 28,
    prepTime: '2 saat',
    isAvailable: true,
    location: 'Kadıköy, İstanbul',
  },
  {
    id: 'f4',
    sellerId: 's2',
    sellerName: 'Fatma Hanım',
    title: 'Ev Yapımı Baklava',
    description: '40 kat incecik yufka, bol fıstıklı ve tam kıvamında şerbetli.',
    price: 250,
    category: 'Tatlılar',
    cuisineType: 'Gaziantep Mutfağı',
    dietaryPreferences: ['vejetaryen'],
    image: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 15,
    prepTime: '1 gün',
    isAvailable: true,
    location: 'Kadıköy, İstanbul',
  },
  {
    id: 'f5',
    sellerId: 's3',
    sellerName: 'Mutfak Sanatları Atölyesi',
    title: 'Mercimek Çorbası',
    description: 'Süzme, tereyağlı ve kıtır ekmekli klasik mercimek çorbası.',
    price: 60,
    category: 'Çorbalar',
    cuisineType: 'Türk Mutfağı',
    dietaryPreferences: ['vejetaryen', 'glutensiz'],
    image: 'https://images.unsplash.com/photo-1547592110-803653f54358?w=800&h=600&fit=crop',
    rating: 4.5,
    reviewCount: 12,
    prepTime: '30 dk',
    isAvailable: true,
    location: 'Şişli, İstanbul',
  },
  {
    id: 'f6',
    sellerId: 's3',
    sellerName: 'Mutfak Sanatları Atölyesi',
    title: 'Glutensiz Sebze Graten',
    description: 'Mevsim sebzeleri ve beşamel sos ile hazırlanan sağlıklı seçenek.',
    price: 140,
    category: 'Diyet & Fit',
    cuisineType: 'Modern Mutfak',
    dietaryPreferences: ['vejetaryen', 'glutensiz'],
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 8,
    prepTime: '45 dk',
    isAvailable: true,
    location: 'Şişli, İstanbul',
  },
];
